apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: cineai
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: cineai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/kavyad-bytes/cineai-backend:05381665d385289d475456acb37a65bae93d95ae
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/cineai
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cineai-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cineai-secrets
                  key: POSTGRES_PASSWORD

            - name: MINIO_URL
              value: http://minio:9000
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cineai-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cineai-secrets
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET
              value: movies

            - name: APP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cineai-secrets
                  key: JWT_SECRET
            - name: APP_JWT_EXPIRATION
              value: "86400000"

          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"