services:
  postgres:
    image: postgres:15
    container_name: cineai-postgres
    environment:
      POSTGRES_DB: cineai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: cineai-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: ./backend
    container_name: cineai-backend
    depends_on:
      - postgres
      - minio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cineai
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: movies
      APP_JWT_SECRET: THIS_IS_A_DEMO_SECRET_KEY_FOR_CINEAISTREAM_JWT_256_BITS
      APP_JWT_EXPIRATION: 86400000
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8081/api
    container_name: cineai-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres_data:
  minio_data: