apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cineai
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: cineai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/kavyad-bytes/cineai-frontend:a3898f7278871d84e9814d65ae80ca7194dd73ad
          ports:
            - containerPort: 80