apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cineai
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/kavyad-bytes/offProjRathinam.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: cineai

  syncPolicy:
    automated:
      prune: true
      selfHeal: true