apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cineai-ingress
  namespace: cineai
spec:
  ingressClassName: nginx
  rules:
    - host: cineai.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80