apiVersion: v1
kind: Secret
metadata:
  name: cineai-secrets
  namespace: cineai
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  JWT_SECRET: THIS_IS_A_DEMO_SECRET_KEY_FOR_CINEAISTREAM_JWT_256_BITS