spring.application.name=devSecOps
server.port=8081

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cineai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${APP_JWT_SECRET:THIS_IS_A_DEMO_SECRET_KEY_FOR_CINEAISTREAM_JWT_256_BITS}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

# MinIO
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:movies}

# Upload limit
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB